version: "3"
services:
  judger:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
    container_name: hustoj-judger
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./backend/upload/problems:/test_case:ro
      - ./judger/log:/log
      # - $PWD/server:/code:ro
      - ./judger/run:/judger
    environment:
      - BACKEND_URL=http://hustoj-backend:8081/api/v1/judge_server_heartbeat
      - SERVICE_URL=http://hustoj-judger:12358
      - TOKEN=acmOJ_shu
    ports:
      - '0.0.0.0:12358:8080'
    networks:
      - webnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: hustoj
    ports:
      - '3307:3306'
    volumes:
      - './mysql/db:/var/lib/mysql'
      - './mysql/conf:/etc/mysql/conf.d'
      - './init/mysql:/docker-entrypoint-initdb.d'
    networks:
      - webnet

  redis:
    image: redis:latest
    container_name: redis
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
    networks:
      - webnet

  backend:
    image: lamhoang1107/hustoj-backend:latest
    container_name: hustoj-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hustoj?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - UPLOAD_PATH=/var/lib/upload
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JUDGER_TOKEN=${JUDGER_TOKEN}
      - JUDGER_URL=http://hustoj-judger:8080
    ports:
      - '8081:8081'
    volumes:
      - ./backend/upload:/var/lib/upload
    networks:
      - webnet
    depends_on:
      - redis
      - mysql


networks:
  webnet:

